create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  request_id text not null unique,
  order_number text not null unique,
  access_code text not null,
  customer_name text not null,
  customer_email text,
  customer_whatsapp text not null,
  delivery_date date not null,
  products text not null,
  items jsonb not null default '[]'::jsonb,
  design_details text not null,
  total numeric(12,2) not null check (total >= 0),
  deposit numeric(12,2) not null check (deposit >= 0),
  balance numeric(12,2) generated always as (total - deposit) stored,
  payment_method text not null,
  payment_detail text,
  status text not null default 'new' check (status in ('new','contacted','confirmed','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_delivery_date_idx on public.orders (delivery_date);

alter table public.orders enable row level security;
drop policy if exists "public orders can be created" on public.orders;
create policy "public orders can be created" on public.orders
  for insert to anon, authenticated
  with check (
    char_length(customer_name) between 2 and 120
    and char_length(customer_whatsapp) between 6 and 40
    and delivery_date >= current_date
    and total >= 0
    and deposit >= 0
  );
grant insert on public.orders to anon, authenticated;
revoke select, update, delete on public.orders from anon, authenticated;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','product_view','add_to_cart','checkout_started','order_submitted','chat_opened','whatsapp_click')),
  session_id text,
  product_id text,
  page text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists analytics_events_occurred_at_idx on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_event_name_idx on public.analytics_events (event_name);

alter table public.analytics_events enable row level security;
drop policy if exists "public analytics events can be created" on public.analytics_events;
create policy "public analytics events can be created" on public.analytics_events
  for insert to anon, authenticated
  with check (char_length(event_name) > 0 and char_length(event_name) <= 40);
grant insert on public.analytics_events to anon, authenticated;
revoke select, update, delete on public.analytics_events from anon, authenticated;

create or replace function public.create_public_order(
  p_request_id text,
  p_customer_name text,
  p_customer_email text,
  p_customer_whatsapp text,
  p_delivery_date date,
  p_products text,
  p_items jsonb,
  p_design_details text,
  p_total numeric,
  p_deposit numeric,
  p_payment_method text,
  p_payment_detail text default null,
  p_access_code text default null
) returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_order_number text := 'PLOP-' || to_char(current_date, 'YYYYMMDD') || '-' || upper(substr(encode(gen_random_bytes(3), 'hex'), 1, 6));
  v_access_code text := coalesce(nullif(p_access_code, ''), lpad((floor(random() * 1000000))::int::text, 6, '0'));
begin
  if char_length(trim(coalesce(p_customer_name, ''))) < 2 then raise exception 'customer_name_invalid'; end if;
  if char_length(trim(coalesce(p_customer_whatsapp, ''))) < 6 then raise exception 'customer_whatsapp_invalid'; end if;
  if p_delivery_date < current_date then raise exception 'delivery_date_invalid'; end if;
  if p_total < 0 or p_deposit < 0 or p_deposit > p_total then raise exception 'amount_invalid'; end if;

  insert into public.orders (
    request_id, order_number, access_code, customer_name, customer_email,
    customer_whatsapp, delivery_date, products, items, design_details,
    total, deposit, payment_method, payment_detail
  ) values (
    p_request_id, v_order_number, v_access_code, trim(p_customer_name), nullif(trim(p_customer_email), ''),
    trim(p_customer_whatsapp), p_delivery_date, trim(p_products), coalesce(p_items, '[]'::jsonb),
    trim(p_design_details), p_total, p_deposit, trim(p_payment_method), nullif(trim(p_payment_detail), '')
  );

  return jsonb_build_object('order_number', v_order_number, 'access_code', v_access_code);
end;
$$;

grant execute on function public.create_public_order(text,text,text,text,date,text,jsonb,text,numeric,numeric,text,text,text) to anon, authenticated;

create or replace function public.track_event(
  p_event_name text,
  p_session_id text default null,
  p_product_id text default null,
  p_metadata jsonb default '{}'::jsonb,
  p_page text default null
) returns void
language sql
set search_path = public
as $$
  insert into public.analytics_events (event_name, session_id, product_id, metadata, page)
  values (p_event_name, nullif(p_session_id, ''), nullif(p_product_id, ''), coalesce(p_metadata, '{}'::jsonb), nullif(p_page, ''));
$$;

grant execute on function public.track_event(text,text,text,jsonb,text) to anon, authenticated;

create or replace function public.get_kpis(p_since timestamptz default now() - interval '30 days', p_until timestamptz default now())
returns jsonb
language sql
stable
set search_path = public
as $$
with period_orders as (
  select * from public.orders where created_at >= p_since and created_at < p_until
), event_counts as (
  select event_name, count(*)::int as count, count(distinct nullif(session_id, ''))::int as sessions
  from public.analytics_events
  where occurred_at >= p_since and occurred_at < p_until
  group by event_name
), product_sales as (
  select item->>'id' as product_id, item->>'name' as product_name,
         sum(coalesce((item->>'qty')::numeric, 0)) as units,
         sum(coalesce((item->>'subtotal')::numeric, 0)) as revenue
  from period_orders, jsonb_array_elements(items) item
  group by item->>'id', item->>'name'
  order by revenue desc
  limit 10
), totals as (
  select count(*)::int as orders,
         count(*) filter (where status in ('confirmed','completed'))::int as confirmed_orders,
         coalesce(sum(total), 0)::numeric as revenue,
         coalesce(sum(deposit), 0)::numeric as deposits,
         coalesce(avg(total), 0)::numeric as average_order_value
  from period_orders
), funnel as (
  select coalesce((select count from event_counts where event_name = 'page_view'), 0) as page_views,
         coalesce((select count from event_counts where event_name = 'add_to_cart'), 0) as add_to_cart,
         coalesce((select count from event_counts where event_name = 'checkout_started'), 0) as checkout_started,
         coalesce((select count from event_counts where event_name = 'order_submitted'), 0) as order_submitted
)
select jsonb_build_object(
  'since', p_since,
  'until', p_until,
  'totals', (select row_to_json(totals) from totals),
  'funnel', (select row_to_json(funnel) from funnel),
  'top_products', coalesce((select jsonb_agg(row_to_json(product_sales)) from product_sales), '[]'::jsonb)
);
$$;

revoke all on function public.get_kpis(timestamptz,timestamptz) from public, anon, authenticated;
grant execute on function public.get_kpis(timestamptz,timestamptz) to service_role;

